Repository openpathsampling/openpathsampling-cli, pull requests merged in 2021-10, with the labels that each got.

#53 switch codecov bash uploader for their github action
  .github/workflows/test-suite.yml
Labels: ci, misc PR

#55 Drop Python 3.6 support
  .github/workflows/test-suite.yml
  setup.cfg
Labels: misc PR

#61 Remove `plugins/` directory
  paths_cli/plugins/__init__.py
Labels: misc PR

#59 pylint/flake8: `paths_cli.compiling`
  paths_cli/compiling/core.py
  paths_cli/compiling/cvs.py
  paths_cli/compiling/engines.py
  paths_cli/compiling/errors.py
  paths_cli/compiling/networks.py
  paths_cli/compiling/plugins.py
  paths_cli/compiling/root_compiler.py
  paths_cli/compiling/schemes.py
  paths_cli/compiling/shooting.py
  paths_cli/compiling/strategies.py
  paths_cli/compiling/tools.py
  paths_cli/compiling/topology.py
  paths_cli/compiling/volumes.py
Labels: misc PR

#63 Wizard: `!quit` command should give option to save
  paths_cli/tests/wizard/test_wizard.py
  paths_cli/wizard/wizard.py
Labels: enhancement

#60 Preserve plugin load order with `OrderedSet`
  paths_cli/tests/test_utils.py
  paths_cli/utils.py
Labels: enhancement
